config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.resources :sessions

  map.with_options(:controller => "sessions") do |sessions|
    sessions.login "/login", :action => "new"
    sessions.logout "/logout", :action => "destroy"
  end

  map.resources :logs

  map.resources :tasks

  map.resources :contracts

  map.resources :users

  map.resources :projects do |projects|
    projects.resources :documents
  end

  map.resources :customers

  map.root :controller => "home"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :customer
  has_many :contracts, :dependent => :destroy
  has_many :documents

  has_many :tasks
  has_many :implementors, :through => :tasks, :source => :owner
  has_and_belongs_to_many :members, :class_name => "User",
    :join_table => "projects_members",
    :association_foreign_key => "member_id"

  named_scope :actives, :conditions => {:active => true}
  named_scope :inactives, :conditions => {:active => false}

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :customer_id
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :load_customers, :only => [:new, :create, :edit, :update]
  before_filter :load_users, :only => [:new, :create, :edit, :update]

  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.find(:all,
      :joins => "LEFT OUTER JOIN customers ON customers.id = projects.customer_id",
      :order => "customers.name")


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        flash[:notice] = 'Project was successfully created.'
        format.html { redirect_to(@project) }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        flash[:notice] = 'Project was successfully updated.'
        format.html { redirect_to(@project) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end


  protected

  def load_customers
    @customers = Customer.find(:all).collect { |c| [c.name, c.id] }
  end

  def load_users
    @users = User.find(:all, :order => "name")
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% form_for(@project) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :customer %><br />
    <%= f.select :customer_id, @customers, :prompt => "Select..." %>
  </p>
  <p>
    <b>Members</b><br />
    <% @users.each do |user| %>
      <%= check_box_tag "project[member_ids][]", user.id, @project.members.include?(user) %>
      <%= user.name %><br />
    <% end %>
  </p>

  <p>
    <%= f.submit @project.new_record? ? "Create" : "Update" %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<% title "Editing project" -%>

<%= render :partial => "form" %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% title "Listing projects" -%>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Customer</th>
    <th>Documents</th>
  </tr>
<% for project in @projects %>
  <tr>
    <td><%=h project.name %></td>
    <td><%=h project.description %></td>
    <td><%=h project.customer.name %></td>
    <td><%= link_to "Documents", project_documents_path(project) %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<% title "New project" -%>

<%= render :partial => "form" %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% title "Project: " + h(@project.name) -%>

<p><%=h(@project.description).gsub!(/\n/, '<br />') %></p>

<p>
  <b>Customer:</b>
  <%=h @project.customer.name %>
</p>

<% unless @project.tasks.empty? %>
  <p>
    <b>Tasks:</b>
    <ul>
      <% @project.tasks.each do |task| %>
        <li><%=h task.title %> - <%=h task.owner.name %></li>
      <% end %>
    </ul>
  </p>
<% end %>

<% unless @project.members.empty? %>
  <p>
    <b>Members:</b>
    <ul>
      <% @project.members.each do |member| %>
        <li><%=h member.name %></li>
      <% end %>
    </ul>
  </p>
<% end %>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>